service: haven-dataflow-service
env: flex
runtime: nodejs
resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
